pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
