pull_request_rules:
  - name: Travis CI - Automatic Merge
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: merge

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge

pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
